"""fix comment model

Revision ID: b539587ee1b9
Revises: 772a0957c904
Create Date: 2026-06-21 22:50:07.434048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b539587ee1b9'
down_revision: Union[str, Sequence[str], None] = '772a0957c904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['owner_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('projects_ibfk_1'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_ibfk_1'), 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'user_id')
    op.add_column('comments', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
